name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Desplega cada vegada que fas un push a la branca 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 1. Configuració de Node.js per a Wasm/Js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Versió compatible amb el teu Wasm/Gradle


      - name: Inject Supabase Secrets for Build # NOU PAS CRUCIAL!
        run: |
          mkdir -p composeApp/src/commonMain/kotlin/cat/happyband/mot/data
          echo "package cat.happyband.mot.data" > composeApp/src/commonMain/kotlin/cat/happyband/mot/data/Config.kt
          echo "const val SUPABASE_URL = \"${{ secrets.SUPABASE_URL }}\"" >> composeApp/src/commonMain/kotlin/cat/happyband/mot/data/Config.kt
          echo "const val SUPABASE_ANON_KEY = \"${{ secrets.SUPABASE_ANON_KEY }}\"" >> composeApp/src/commonMain/kotlin/cat/happyband/mot/data/Config.kt
          echo "const val TABLE_NAME = \"mot_results\"" >> composeApp/src/commonMain/kotlin/cat/happyband/mot/data/Config.kt

      # 2. Executar la tasca de producció de Gradle
      - name: Build WasmJs Distribution
        run: ./gradlew wasmJsBrowserDistribution
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      # 3. Desplegar els fitxers construïts a la branca gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Ruta on Gradle ha posat els teus fitxers de producció
          publish_dir: ./composeApp/build/dist/wasmJs/productionExecutable
          # Per garantir que sempre es fa un clean deploy
          force_orphan: true